kind = "web"
previewPath = "/"
title = "My Portfolio"
version = "1.0.0"
id = "artifacts/my-portfolio"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21235

[services.development]
run = "pnpm --filter @workspace/my-portfolio run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/my-portfolio", "run", "build" ]
serve = "static"
publicDir = "artifacts/my-portfolio/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21235"
BASE_PATH = "/"
